modLoader="javafml"
loaderVersion="[36,)"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${file.jarVersion}"
displayName="${mod_Name}"
logoFile="${mod_id}.png"
credits="${mod_credits}"
authors="${mod_Authors}"
description='''
${mod_description}
'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mod_mincecraft_version)"
    ordering="NONE"
    side="BOTH"
