modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/CoolCLK/SkyDimension/issues/new/"
[[mods]]
modId="skydimension"
version="1.0.6"
displayName="Sky Dimension"
updateJSONURL="https://github.com/CoolCLK/SkyDimension/raw/1.14.4/src/main/resources/update.json"
displayURL="https://github.com/CoolCLK/SkyDimension"
logoFile=""
credits="Thanks the original authors, they create the sky dimension."
authors="CoolCLK"
description='''Re-add Sky Dimension from Beta version.'''
[[dependencies.skydimension]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.skydimension]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"