modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
issueTrackerURL="https://github.com/CoolCLK/SkyDimension/issues/new/"
[[mods]]
modId="${mod_id}"
version="${file.jarVersion}"
displayName="${mod_name}"
updateJSONURL="${mod_update_url}"
displayURL="${mod_url}"
logoFile=""
credits="${mod_credits}"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_loader_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${mod_minecraft_version_range}"
    ordering="NONE"
    side="BOTH"